import type { Metadata } from "next";
import { sora } from "./fonts";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Dine MerketPlace",
  description: "Generated by zesh786 on Github",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Header/>
        <main className="px-6 mx-3 lg:px-16 lg:mx-8">
        {children}
        </main>
        <Footer />
        </body>
    </html>
  );
}